#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Template: Linux setup for ibcmd-based matrix/smoke runs.
# Copy this file to `ibcmd-local.sh`, adjust paths, then run:
#   source ./ibcmd-local.sh
# ============================================================================

# Path to ibcmd binary (1C platform 8.3.27+).
export IBCMD_PATH="/path/to/1c/bin/ibcmd"

# Path to infobase YAML (usually generated by: ibcmd server config init ... --out=...).
export IBCMD_INFOBASE_CONFIG="/path/to/ibcmd-infobase.yml"

# Optional 1C credentials (uncomment if needed):
# export IBCMD_USER="Администратор"
# export IBCMD_PASSWORD=""

# Optional timeout for ibcmd subprocesses (ms):
# export IBCMD_TIMEOUT_MS="600000"

# Optional: enforce config check with --force.
# export IBCMD_CONFIG_CHECK_FORCE="1"

# Recommended defaults for local matrix smoke:
export INSTRUMENT_IBCMD_NONFATAL="1"
export MATRIX_FULL="1"
unset MATRIX_SLICE_LIMIT
export MATRIX_NESTED="1"

echo "IBCMD env loaded."
echo "  IBCMD_PATH=${IBCMD_PATH}"
echo "  IBCMD_INFOBASE_CONFIG=${IBCMD_INFOBASE_CONFIG}"
