export const coreSuiteFiles: string[] = [
  'suite/designerParser.test.js',
  'suite/formatDetector.test.js',
  'suite/formEditorTitle.test.js',
  'suite/formXmlParser.test.js',
  'suite/metadataParser.test.js',
  'suite/xmlParser.test.js',
  'suite/xmlWriter.test.js',
  'suite/xmlWriter.tabularColumn.test.js',
  'suite/elementNameValidator.test.js',
  'suite/referenceFinder.test.js',
  'suite/elementOperations.test.js',
  'suite/registerRecorderDocumentLinker.test.js',
  'suite/matrixTargetPredicate.test.js',
  'suite/dataProcessorOperations.test.js',
  'suite/diagnosticsSummary.test.js',
  'suite/configHelpers.test.js',
  'suite/formDragBugCondition.test.js',
  'suite/formDragPreservation.test.js',
  'suite/formTreeRootDragBugCondition.test.js',
  'suite/formTreeRootDragPreservation.test.js',
  'suite/formModelUtils.test.js',
  'suite/formModelCommands.test.js',
  'suite/roleXmlParser.test.js',
  'suite/roleXmlSerializer.test.js',
  'suite/rightsValidator.test.js',
  'suite/filterUtils.test.js',
  'suite/rightsUpdateUtils.test.js',
  'suite/rightsXmlTemplates.test.js',
  'suite/rightsEditor.integration.test.js',
  'suite/typeParser.test.js',
  'suite/subsystemTreeBuilder.test.js',
  'suite/treeNormalization.test.js',
  'suite/typeFormatterAndFilterState.test.js',
  'suite/configurationXmlUpdater.test.js',
  'suite/designerTemplateServices.test.js',
  'suite/servicesCoverage.test.js',
  'suite/fixtureMatrix.test.js',
  ...(process.env.SKIP_CONTAINER_MATRIX_E2E === '1'
    ? []
    : ['suite/containerMatrix.e2e.test.js']),
];
