// src/rules/metadata/chartOfCharacteristicTypesRules.ts
// Rules for ChartOfCharacteristicTypes metadata object (Designer format).
import { MetadataObjectRules } from '../types';

export const chartOfCharacteristicTypesRules: MetadataObjectRules = {
    rootTag: 'ChartOfCharacteristicTypes',
    namespaces: {
        'xmlns': 'http://v8.1c.ru/8.3/MDClasses',
        'xmlns:v8': 'http://v8.1c.ru/8.1/data/core',
        'xmlns:xr': 'http://v8.1c.ru/8.3/xcf/readable',
        'xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
    },
    hasChildObjects: true,
    properties: {
        name: { type: 'string', order: 1, xml: 'Name', yaml: 'Имя', required: true },
        synonym: { type: 'I8nText', order: 2, xml: 'Synonym', yaml: 'Синоним' },
        comment: { type: 'string', order: 3, xml: 'Comment', yaml: 'Комментарий', defaultValueXML: '' },
        useStandardCommands: { type: 'boolean', order: 4, xml: 'UseStandardCommands', defaultValueXML: true },
        includeHelpInContents: { type: 'boolean', order: 5, xml: 'IncludeHelpInContents', defaultValueXML: false },
        characteristicExtValues: { type: 'string', order: 6, xml: 'CharacteristicExtValues', defaultValueXML: '' },
        type: {
            type: 'TypeDescription',
            order: 7,
            xml: 'Type',
            defaultValueXML: {
                'v8:Type': 'xs:string',
                'v8:StringQualifiers': {
                    'v8:Length': 10,
                    'v8:AllowedLength': 'Variable',
                },
            },
        },
        hierarchical: { type: 'boolean', order: 8, xml: 'Hierarchical', yaml: 'Иерархический', defaultValueXML: false },
        foldersOnTop: { type: 'boolean', order: 9, xml: 'FoldersOnTop', defaultValueXML: true },
        codeLength: { type: 'number', order: 10, xml: 'CodeLength', yaml: 'ДлинаКода', defaultValueXML: 9 },
        codeAllowedLength: { type: 'SystemEnumeration', order: 11, xml: 'CodeAllowedLength', defaultValueXML: 'Variable', typeSE: 'CodeAllowedLength' },
        descriptionLength: { type: 'number', order: 12, xml: 'DescriptionLength', yaml: 'ДлинаНаименования', defaultValueXML: 25 },
        codeSeries: { type: 'SystemEnumeration', order: 13, xml: 'CodeSeries', defaultValueXML: 'WholeCharacteristicKind', typeSE: 'CodeSeries' },
        checkUnique: { type: 'boolean', order: 14, xml: 'CheckUnique', defaultValueXML: true },
        autonumbering: { type: 'boolean', order: 15, xml: 'Autonumbering', yaml: 'Автонумерация', defaultValueXML: true },
        defaultPresentation: { type: 'SystemEnumeration', order: 16, xml: 'DefaultPresentation', defaultValueXML: 'AsDescription', typeSE: 'DefaultPresentation' },
        characteristics: { type: 'string', order: 17, xml: 'Characteristics', defaultValueXML: '' },
        predefinedDataUpdate: { type: 'SystemEnumeration', order: 18, xml: 'PredefinedDataUpdate', defaultValueXML: 'Auto', typeSE: 'PredefinedDataUpdate' },
        editType: { type: 'SystemEnumeration', order: 19, xml: 'EditType', defaultValueXML: 'InDialog', typeSE: 'EditType' },
        quickChoice: { type: 'boolean', order: 20, xml: 'QuickChoice', defaultValueXML: false },
        choiceMode: { type: 'SystemEnumeration', order: 21, xml: 'ChoiceMode', defaultValueXML: 'BothWays', typeSE: 'ChoiceMode' },
        inputByString: { type: 'InternalInfo', order: 22, xml: 'InputByString', defaultValueXML: { 'xr:Field': ['ChartOfCharacteristicTypes.{Name}.StandardAttribute.Description', 'ChartOfCharacteristicTypes.{Name}.StandardAttribute.Code'] } },
        createOnInput: { type: 'SystemEnumeration', order: 23, xml: 'CreateOnInput', defaultValueXML: 'DontUse', typeSE: 'CreateOnInput' },
        searchStringModeOnInputByString: { type: 'SystemEnumeration', order: 24, xml: 'SearchStringModeOnInputByString', defaultValueXML: 'Begin', typeSE: 'SearchStringModeOnInputByString' },
        choiceDataGetModeOnInputByString: { type: 'SystemEnumeration', order: 25, xml: 'ChoiceDataGetModeOnInputByString', defaultValueXML: 'Directly', typeSE: 'ChoiceDataGetModeOnInputByString' },
        fullTextSearchOnInputByString: { type: 'SystemEnumeration', order: 26, xml: 'FullTextSearchOnInputByString', defaultValueXML: 'DontUse', typeSE: 'FullTextSearchOnInputByString' },
        choiceHistoryOnInput: { type: 'SystemEnumeration', order: 27, xml: 'ChoiceHistoryOnInput', defaultValueXML: 'Auto', typeSE: 'ChoiceHistoryOnInput' },
        defaultObjectForm: { type: 'string', order: 28, xml: 'DefaultObjectForm', defaultValueXML: '' },
        defaultFolderForm: { type: 'string', order: 29, xml: 'DefaultFolderForm', defaultValueXML: '' },
        defaultListForm: { type: 'string', order: 30, xml: 'DefaultListForm', defaultValueXML: '' },
        defaultChoiceForm: { type: 'string', order: 31, xml: 'DefaultChoiceForm', defaultValueXML: '' },
        defaultFolderChoiceForm: { type: 'string', order: 32, xml: 'DefaultFolderChoiceForm', defaultValueXML: '' },
        auxiliaryObjectForm: { type: 'string', order: 33, xml: 'AuxiliaryObjectForm', defaultValueXML: '' },
        auxiliaryFolderForm: { type: 'string', order: 34, xml: 'AuxiliaryFolderForm', defaultValueXML: '' },
        auxiliaryListForm: { type: 'string', order: 35, xml: 'AuxiliaryListForm', defaultValueXML: '' },
        auxiliaryChoiceForm: { type: 'string', order: 36, xml: 'AuxiliaryChoiceForm', defaultValueXML: '' },
        auxiliaryFolderChoiceForm: { type: 'string', order: 37, xml: 'AuxiliaryFolderChoiceForm', defaultValueXML: '' },
        basedOn: { type: 'string', order: 38, xml: 'BasedOn', defaultValueXML: '' },
        dataLockFields: { type: 'string', order: 39, xml: 'DataLockFields', defaultValueXML: '' },
        dataLockControlMode: { type: 'SystemEnumeration', order: 40, xml: 'DataLockControlMode', defaultValueXML: 'Managed', typeSE: 'DataLockControlMode' },
        fullTextSearch: { type: 'SystemEnumeration', order: 41, xml: 'FullTextSearch', defaultValueXML: 'Use', typeSE: 'FullTextSearch' },
        objectPresentation: { type: 'string', order: 42, xml: 'ObjectPresentation', defaultValueXML: '' },
        extendedObjectPresentation: { type: 'string', order: 43, xml: 'ExtendedObjectPresentation', defaultValueXML: '' },
        listPresentation: { type: 'I8nText', order: 44, xml: 'ListPresentation', defaultValueXML: '{Synonym_ru}' },
        extendedListPresentation: { type: 'I8nText', order: 45, xml: 'ExtendedListPresentation', defaultValueXML: '{Synonym_ru}' },
        explanation: { type: 'string', order: 46, xml: 'Explanation', defaultValueXML: '' },
        dataHistory: { type: 'SystemEnumeration', order: 47, xml: 'DataHistory', defaultValueXML: 'DontUse', typeSE: 'DataHistory' },
        updateDataHistoryImmediatelyAfterWrite: { type: 'boolean', order: 48, xml: 'UpdateDataHistoryImmediatelyAfterWrite', defaultValueXML: false },
        executeAfterWriteDataHistoryVersionProcessing: { type: 'boolean', order: 49, xml: 'ExecuteAfterWriteDataHistoryVersionProcessing', defaultValueXML: false },
        standardAttributes: { type: 'StandardAttributeDescriptions', order: 50, xml: 'StandardAttributes', defaultValueXML: undefined },
    },
};
