// src/rules/metadata/documentRules.ts
// Rules for Document metadata object (Designer format).
import { MetadataObjectRules } from '../types';

export const documentRules: MetadataObjectRules = {
    rootTag: 'Document',
    namespaces: {
        'xmlns': 'http://v8.1c.ru/8.3/MDClasses',
        'xmlns:v8': 'http://v8.1c.ru/8.1/data/core',
        'xmlns:xr': 'http://v8.1c.ru/8.3/xcf/readable',
        'xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
    },
    hasChildObjects: true,
    properties: {
        autonumbering: { type: 'boolean', order: 1, xml: 'Autonumbering', yaml: 'Автонумерация', defaultValueXML: true },
        auxiliaryChoiceForm: { type: 'string', order: 2, xml: 'AuxiliaryChoiceForm', defaultValueXML: '' },
        auxiliaryListForm: { type: 'string', order: 3, xml: 'AuxiliaryListForm', defaultValueXML: '' },
        auxiliaryObjectForm: { type: 'string', order: 4, xml: 'AuxiliaryObjectForm', defaultValueXML: '' },
        basedOn: { type: 'string', order: 5, xml: 'BasedOn', defaultValueXML: '' },
        characteristics: { type: 'string', order: 6, xml: 'Characteristics', defaultValueXML: '' },
        checkUnique: { type: 'boolean', order: 7, xml: 'CheckUnique', defaultValueXML: true },
        choiceDataGetModeOnInputByString: { type: 'SystemEnumeration', order: 8, xml: 'ChoiceDataGetModeOnInputByString', defaultValueXML: 'Directly', typeSE: 'ChoiceDataGetModeOnInputByString' },
        choiceHistoryOnInput: { type: 'SystemEnumeration', order: 9, xml: 'ChoiceHistoryOnInput', defaultValueXML: 'Auto', typeSE: 'ChoiceHistoryOnInput' },
        comment: { type: 'string', order: 10, xml: 'Comment', yaml: 'Комментарий', defaultValueXML: '' },
        createOnInput: { type: 'SystemEnumeration', order: 11, xml: 'CreateOnInput', defaultValueXML: 'Use', typeSE: 'CreateOnInput' },
        dataHistory: { type: 'SystemEnumeration', order: 12, xml: 'DataHistory', defaultValueXML: 'DontUse', typeSE: 'DataHistory' },
        dataLockControlMode: { type: 'SystemEnumeration', order: 13, xml: 'DataLockControlMode', defaultValueXML: 'Managed', typeSE: 'DataLockControlMode' },
        dataLockFields: { type: 'string', order: 14, xml: 'DataLockFields', defaultValueXML: '' },
        defaultChoiceForm: { type: 'string', order: 15, xml: 'DefaultChoiceForm', defaultValueXML: '' },
        defaultListForm: { type: 'string', order: 16, xml: 'DefaultListForm', defaultValueXML: '' },
        defaultObjectForm: { type: 'string', order: 17, xml: 'DefaultObjectForm', defaultValueXML: '' },
        executeAfterWriteDataHistoryVersionProcessing: { type: 'boolean', order: 18, xml: 'ExecuteAfterWriteDataHistoryVersionProcessing', defaultValueXML: false },
        explanation: { type: 'string', order: 19, xml: 'Explanation', defaultValueXML: '' },
        extendedListPresentation: { type: 'string', order: 20, xml: 'ExtendedListPresentation', defaultValueXML: '' },
        extendedObjectPresentation: { type: 'string', order: 21, xml: 'ExtendedObjectPresentation', defaultValueXML: '' },
        fullTextSearch: { type: 'SystemEnumeration', order: 22, xml: 'FullTextSearch', defaultValueXML: 'Use', typeSE: 'FullTextSearch' },
        fullTextSearchOnInputByString: { type: 'SystemEnumeration', order: 23, xml: 'FullTextSearchOnInputByString', defaultValueXML: 'DontUse', typeSE: 'FullTextSearchOnInputByString' },
        includeHelpInContents: { type: 'boolean', order: 24, xml: 'IncludeHelpInContents', defaultValueXML: false },
        inputByString: { type: 'InternalInfo', order: 25, xml: 'InputByString', defaultValueXML: { 'xr:Field': 'Document.{Name}.StandardAttribute.Number' } },
        listPresentation: { type: 'I8nText', order: 26, xml: 'ListPresentation', defaultValueXML: '{Synonym_ru}' },
        name: { type: 'string', order: 27, xml: 'Name', yaml: 'Имя', required: true },
        numberAllowedLength: { type: 'SystemEnumeration', order: 28, xml: 'NumberAllowedLength', defaultValueXML: 'Variable', typeSE: 'NumberAllowedLength' },
        numberLength: { type: 'number', order: 29, xml: 'NumberLength', yaml: 'ДлинаНомера', defaultValueXML: 11 },
        numberPeriodicity: { type: 'SystemEnumeration', order: 30, xml: 'NumberPeriodicity', defaultValueXML: 'Year', typeSE: 'NumberPeriodicity' },
        numberType: { type: 'SystemEnumeration', order: 31, xml: 'NumberType', yaml: 'ТипНомера', defaultValueXML: 'String', typeSE: 'NumberType' },
        numerator: { type: 'string', order: 32, xml: 'Numerator', defaultValueXML: '' },
        objectPresentation: { type: 'string', order: 33, xml: 'ObjectPresentation', defaultValueXML: '' },
        postInPrivilegedMode: { type: 'boolean', order: 34, xml: 'PostInPrivilegedMode', defaultValueXML: true },
        posting: { type: 'SystemEnumeration', order: 35, xml: 'Posting', yaml: 'Проведение', defaultValueXML: 'Allow', typeSE: 'Posting' },
        realTimePosting: { type: 'SystemEnumeration', order: 36, xml: 'RealTimePosting', defaultValueXML: 'Allow', typeSE: 'RealTimePosting' },
        registerRecords: { type: 'string', order: 37, xml: 'RegisterRecords', defaultValueXML: '' },
        registerRecordsDeletion: { type: 'SystemEnumeration', order: 38, xml: 'RegisterRecordsDeletion', defaultValueXML: 'AutoDeleteOff', typeSE: 'RegisterRecordsDeletion' },
        registerRecordsWritingOnPost: { type: 'SystemEnumeration', order: 39, xml: 'RegisterRecordsWritingOnPost', defaultValueXML: 'WriteSelected', typeSE: 'RegisterRecordsWritingOnPost' },
        searchStringModeOnInputByString: { type: 'SystemEnumeration', order: 40, xml: 'SearchStringModeOnInputByString', defaultValueXML: 'Begin', typeSE: 'SearchStringModeOnInputByString' },
        sequenceFilling: { type: 'SystemEnumeration', order: 41, xml: 'SequenceFilling', defaultValueXML: 'AutoFill', typeSE: 'SequenceFilling' },
        standardAttributes: { type: 'StandardAttributeDescriptions', order: 42, xml: 'StandardAttributes', defaultValueXML: undefined },
        synonym: { type: 'I8nText', order: 43, xml: 'Synonym', yaml: 'Синоним' },
        unpostInPrivilegedMode: { type: 'boolean', order: 44, xml: 'UnpostInPrivilegedMode', defaultValueXML: true },
        updateDataHistoryImmediatelyAfterWrite: { type: 'boolean', order: 45, xml: 'UpdateDataHistoryImmediatelyAfterWrite', defaultValueXML: false },
        useStandardCommands: { type: 'boolean', order: 46, xml: 'UseStandardCommands', defaultValueXML: false },
    },
};
