// src/rules/metadata/taskRules.ts
// Rules for Task metadata object (Designer format).
import { MetadataObjectRules } from '../types';

export const taskRules: MetadataObjectRules = {
    rootTag: 'Task',
    namespaces: {
        'xmlns': 'http://v8.1c.ru/8.3/MDClasses',
        'xmlns:v8': 'http://v8.1c.ru/8.1/data/core',
        'xmlns:xr': 'http://v8.1c.ru/8.3/xcf/readable',
        'xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
    },
    hasChildObjects: true,
    properties: {
        addressing: { type: 'string', order: 1, xml: 'Addressing', yaml: 'Адресация', defaultValueXML: '' },
        autonumbering: { type: 'boolean', order: 2, xml: 'Autonumbering', yaml: 'Автонумерация', defaultValueXML: true },
        auxiliaryChoiceForm: { type: 'string', order: 3, xml: 'AuxiliaryChoiceForm', defaultValueXML: '' },
        auxiliaryListForm: { type: 'string', order: 4, xml: 'AuxiliaryListForm', defaultValueXML: '' },
        auxiliaryObjectForm: { type: 'string', order: 5, xml: 'AuxiliaryObjectForm', defaultValueXML: '' },
        basedOn: { type: 'string', order: 6, xml: 'BasedOn', defaultValueXML: '' },
        characteristics: { type: 'string', order: 7, xml: 'Characteristics', defaultValueXML: '' },
        checkUnique: { type: 'boolean', order: 8, xml: 'CheckUnique', defaultValueXML: true },
        choiceDataGetModeOnInputByString: { type: 'SystemEnumeration', order: 9, xml: 'ChoiceDataGetModeOnInputByString', defaultValueXML: 'Directly', typeSE: 'ChoiceDataGetModeOnInputByString' },
        choiceHistoryOnInput: { type: 'SystemEnumeration', order: 10, xml: 'ChoiceHistoryOnInput', defaultValueXML: 'Auto', typeSE: 'ChoiceHistoryOnInput' },
        comment: { type: 'string', order: 11, xml: 'Comment', yaml: 'Комментарий', defaultValueXML: '' },
        createOnInput: { type: 'SystemEnumeration', order: 12, xml: 'CreateOnInput', defaultValueXML: 'DontUse', typeSE: 'CreateOnInput' },
        currentPerformer: { type: 'string', order: 13, xml: 'CurrentPerformer', yaml: 'ТекущийИсполнитель', defaultValueXML: '' },
        dataHistory: { type: 'SystemEnumeration', order: 14, xml: 'DataHistory', defaultValueXML: 'DontUse', typeSE: 'DataHistory' },
        dataLockControlMode: { type: 'SystemEnumeration', order: 15, xml: 'DataLockControlMode', defaultValueXML: 'Managed', typeSE: 'DataLockControlMode' },
        dataLockFields: { type: 'InternalInfo', order: 16, xml: 'DataLockFields', defaultValueXML: { 'xr:Field': 'Task.{Name}.StandardAttribute.BusinessProcess' } },
        defaultChoiceForm: { type: 'string', order: 17, xml: 'DefaultChoiceForm', defaultValueXML: '' },
        defaultListForm: { type: 'string', order: 18, xml: 'DefaultListForm', defaultValueXML: '' },
        defaultObjectForm: { type: 'string', order: 19, xml: 'DefaultObjectForm', defaultValueXML: '' },
        defaultPresentation: { type: 'SystemEnumeration', order: 20, xml: 'DefaultPresentation', defaultValueXML: 'AsDescription', typeSE: 'DefaultPresentation' },
        descriptionLength: { type: 'number', order: 21, xml: 'DescriptionLength', yaml: 'ДлинаНаименования', defaultValueXML: 150 },
        editType: { type: 'SystemEnumeration', order: 22, xml: 'EditType', defaultValueXML: 'InDialog', typeSE: 'EditType' },
        executeAfterWriteDataHistoryVersionProcessing: { type: 'boolean', order: 23, xml: 'ExecuteAfterWriteDataHistoryVersionProcessing', defaultValueXML: false },
        explanation: { type: 'string', order: 24, xml: 'Explanation', defaultValueXML: '' },
        extendedListPresentation: { type: 'I8nText', order: 25, xml: 'ExtendedListPresentation', defaultValueXML: '{Synonym_ru}' },
        extendedObjectPresentation: { type: 'string', order: 26, xml: 'ExtendedObjectPresentation', defaultValueXML: '' },
        fullTextSearch: { type: 'SystemEnumeration', order: 27, xml: 'FullTextSearch', defaultValueXML: 'Use', typeSE: 'FullTextSearch' },
        fullTextSearchOnInputByString: { type: 'SystemEnumeration', order: 28, xml: 'FullTextSearchOnInputByString', defaultValueXML: 'DontUse', typeSE: 'FullTextSearchOnInputByString' },
        includeHelpInContents: { type: 'boolean', order: 29, xml: 'IncludeHelpInContents', defaultValueXML: true },
        inputByString: { type: 'InternalInfo', order: 30, xml: 'InputByString', defaultValueXML: { 'xr:Field': 'Task.{Name}.StandardAttribute.Description' } },
        listPresentation: { type: 'I8nText', order: 31, xml: 'ListPresentation', defaultValueXML: '{Synonym_ru}' },
        mainAddressingAttribute: { type: 'string', order: 32, xml: 'MainAddressingAttribute', yaml: 'ОсновнойРеквизитАдресации', defaultValueXML: '' },
        name: { type: 'string', order: 33, xml: 'Name', yaml: 'Имя', required: true },
        numberAllowedLength: { type: 'SystemEnumeration', order: 34, xml: 'NumberAllowedLength', defaultValueXML: 'Fixed', typeSE: 'NumberAllowedLength' },
        numberLength: { type: 'number', order: 35, xml: 'NumberLength', yaml: 'ДлинаНомера', defaultValueXML: 14 },
        numberType: { type: 'SystemEnumeration', order: 36, xml: 'NumberType', yaml: 'ТипНомера', defaultValueXML: 'String', typeSE: 'TaskNumberType' },
        objectPresentation: { type: 'string', order: 37, xml: 'ObjectPresentation', defaultValueXML: '' },
        searchStringModeOnInputByString: { type: 'SystemEnumeration', order: 38, xml: 'SearchStringModeOnInputByString', defaultValueXML: 'Begin', typeSE: 'SearchStringModeOnInputByString' },
        standardAttributes: { type: 'StandardAttributeDescriptions', order: 39, xml: 'StandardAttributes', defaultValueXML: undefined },
        synonym: { type: 'I8nText', order: 40, xml: 'Synonym', yaml: 'Синоним' },
        taskNumberAutoPrefix: { type: 'SystemEnumeration', order: 41, xml: 'TaskNumberAutoPrefix', yaml: 'АвтопрефиксНомераЗадачи', defaultValueXML: 'BusinessProcessNumber', typeSE: 'TaskNumberAutoPrefix' },
        updateDataHistoryImmediatelyAfterWrite: { type: 'boolean', order: 42, xml: 'UpdateDataHistoryImmediatelyAfterWrite', defaultValueXML: false },
        useStandardCommands: { type: 'boolean', order: 43, xml: 'UseStandardCommands', defaultValueXML: false },
    },
};
